
package calcws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NoteServiceService", targetNamespace = "http://calcws/", wsdlLocation = "http://localhost:9191/noteservice?wsdl")
public class NoteServiceService
    extends Service
{

    private final static URL NOTESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException NOTESERVICESERVICE_EXCEPTION;
    private final static QName NOTESERVICESERVICE_QNAME = new QName("http://calcws/", "NoteServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9191/noteservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTESERVICESERVICE_WSDL_LOCATION = url;
        NOTESERVICESERVICE_EXCEPTION = e;
    }

    public NoteServiceService() {
        super(__getWsdlLocation(), NOTESERVICESERVICE_QNAME);
    }

    public NoteServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTESERVICESERVICE_QNAME, features);
    }

    public NoteServiceService(URL wsdlLocation) {
        super(wsdlLocation, NOTESERVICESERVICE_QNAME);
    }

    public NoteServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTESERVICESERVICE_QNAME, features);
    }

    public NoteServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NoteServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NoteService
     */
    @WebEndpoint(name = "NoteServicePort")
    public NoteService getNoteServicePort() {
        return super.getPort(new QName("http://calcws/", "NoteServicePort"), NoteService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NoteService
     */
    @WebEndpoint(name = "NoteServicePort")
    public NoteService getNoteServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://calcws/", "NoteServicePort"), NoteService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTESERVICESERVICE_EXCEPTION!= null) {
            throw NOTESERVICESERVICE_EXCEPTION;
        }
        return NOTESERVICESERVICE_WSDL_LOCATION;
    }

}
