
package calcws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NoteService", targetNamespace = "http://calcws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NoteService {


    /**
     * 
     * @return
     *     returns java.util.List<calcws.Note>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNotes", targetNamespace = "http://calcws/", className = "calcws.GetNotes")
    @ResponseWrapper(localName = "getNotesResponse", targetNamespace = "http://calcws/", className = "calcws.GetNotesResponse")
    @Action(input = "http://calcws/NoteService/getNotesRequest", output = "http://calcws/NoteService/getNotesResponse")
    public List<Note> getNotes();

    /**
     * 
     * @param text
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNote", targetNamespace = "http://calcws/", className = "calcws.AddNote")
    @ResponseWrapper(localName = "addNoteResponse", targetNamespace = "http://calcws/", className = "calcws.AddNoteResponse")
    @Action(input = "http://calcws/NoteService/addNoteRequest", output = "http://calcws/NoteService/addNoteResponse")
    public boolean addNote(
        @WebParam(name = "text", targetNamespace = "")
        String text);

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeNote", targetNamespace = "http://calcws/", className = "calcws.RemoveNote")
    @ResponseWrapper(localName = "removeNoteResponse", targetNamespace = "http://calcws/", className = "calcws.RemoveNoteResponse")
    @Action(input = "http://calcws/NoteService/removeNoteRequest", output = "http://calcws/NoteService/removeNoteResponse")
    public boolean removeNote(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
